Tienda/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('', include('apiapp.urls')),
    
    path('accounts/',include('django.contrib.auth.urls')),
]



urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


admin.site.site_title = "Tienda"
admin.site.site_header = "Administracion de la tienda"
admin.site.index_title = "Modulos de la tienda"

app/urls.py
from unicodedata import name
from django.urls import path
from .views import *


urlpatterns = [
    path('', index,name="index"),
    path('perrito/',perrito,name="perrito"),
    path('gato/',gato,name="gato"),
    path('pajaros/',pajaros,name="pajaros"),
    path('todos/',todos,name="todos"),
    path('suscripcion/',suscripcion,name="suscripcion"),
    path('ayuda/',ayuda,name="ayuda"),
    path('registro/',registro,name="registro"),
    path('codigo2/',codigo2,name="codigo2"),

    path('usu_ini/', usuario_iniciado, name="usu_ini" ),
    path('perrito_ini/',perrito_ini,name="perrito_ini"),
    path('gato_ini/',gato_ini,name="gato_ini"),
    path('pajaro_ini/',pajaros_ini,name="pajaros_ini"),
    path('suscripcion_ini/',suscripcion_ini,name="suscripcion_ini"),
    path('ayuda_ini/',ayuda_ini,name="ayuda_ini"),
    path('todo_ini/',todo_ini,name='todo_ini'),
    path('carrito/', carrito, name="carrito"),
    path('cuenta/', cuenta, name="cuenta"),
    path('Historial/', Historial, name="Historial"),
    path('pago/', pago, name="pago"),
    path('seguimiento/', seguimiento, name="seguimiento"),
    path('seguimiento2/', seguimiento2, name="seguimiento2"),
    
    path('conf_pago/', conf_pago, name="conf_pago"),
   

    path('agregar_p', agregar_p, name="agregar_p"),
    path('modificar_producto/<codigo>/', modificar_producto, name="modificar_producto"),
    path('eliminar_producto/<codigo>/', eliminar_producto, name="eliminar_producto"),
    path('listar_producto/', listar_producto, name="listar_producto"),
    path('iniciar_sesion/', iniciar_sesion, name="iniciar_sesion"),

    
 
    path('eliminar_carrito/<id>/', eliminar_carrito, name="eliminar_carrito"),


    path('desuscripcion/', desuscripcion, name="desuscripcion"),

    path('registro/', registro, name="registro"),
    
 


]

app/models.py
from distutils.command.upload import upload
from django.db import models

# Create your models here.

class TipoProducto(models.Model):
    tipo = models.CharField(max_length=20)

    def __str__(self):
        return self.tipo
    
    class Meta:
       db_table = 'db_tipo_producto'
'''
class TipoUsuario(models.Model):
    tipo = models.CharField(max_length=20)

    def __str__(self):
        return self.tipo
    
    class Meta:
       db_table = 'db_tipo_producto'
'''

class Producto(models.Model):
    codigo = models.IntegerField(null=False,primary_key=True)
    nombre = models.CharField(max_length=20)
    marca = models.CharField(max_length=20)
    precio = models.IntegerField()
    stock = models.IntegerField()
    tipo = models.ForeignKey(TipoProducto, on_delete=models.CASCADE)   
    imagen = models.ImageField(upload_to="productos", null=True)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    def __str__(self):
        return self.nombre

    class Meta:
       db_table = 'db_producto'


class Items_Carrito(models.Model):
    nombre_producto = models.CharField(max_length=40)
    precio_producto = models.IntegerField()
    imagen = models.ImageField(null=True)
    stock = models.IntegerField(null=True)
    class Meta:
        db_table = 'db_Items_Carrito'


class Historial_Items(models.Model):
    nombre_producto = models.CharField(max_length=40)
    precio_producto = models.IntegerField()
    imagen = models.ImageField(null=True)
    class Meta:
        db_table = 'db_historial'






class Usuarios(models.Model):
    nombre = models.CharField(max_length=200)
    apellido = models.CharField(max_length=200)
    rut = models.CharField(max_length=200)
    #tipo =  models.ForeignKey(TipoUsuario, on_delete=models.CASCADE)   
    direccion = models.CharField(max_length=200)
    correo = models.CharField(max_length=200)
    contrasenia = models.CharField(max_length=200) 


    class Meta:
       db_table = 'db_usuario'

class Suscripcion(models.Model):
    username = models.CharField(max_length=200)
    suscrito = models.BooleanField(default=True)

    class Meta:
       db_table = 'db_suscripcion'



# python manage.py makemigrations = crea el script de la bd
# python manage.py migrate

app/templates/app/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% static 'app/css/style.css' %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PetShop</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    <link rel="stylesheet" href="{% static 'app/css/style.css' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/11.4.8/sweetalert2.min.js" integrity="sha512-7x7HoEikRZhV0FAORWP+hrUzl75JW/uLHBbg2kHnPdFmScpIeHY0ieUVSacjusrKrlA/RsA2tDOBvisFmKc3xw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/11.4.8/sweetalert2.css" integrity="sha512-40/Lc5CTd+76RzYwpttkBAJU68jKKQy4mnPI52KKOHwRBsGcvQct9cIqpWT/XGLSsQFAcuty1fIuNgqRoZTiGQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="{% static 'app/js/mensajes.js' %}"></script>
</head>

<body>

  
    <div class="modal " id="IniSes">
        <div class="modal-dialog">
          <div class="modal-content">
      
            <div class="modal-header">
              <h4 class="modal-title">Iniciar sesión</h4>
              <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
      
            <div class="modal-body text-center">
                <img src="" alt="">
                <form action="suscriptor.html" method="get">
    
                    <div class="form-group">
                        <label for="txtUser">Usuario: </label>
                        <input placeholder="Ej: n.asdasdf" class="form-control" type="text" id="txtUser" name="textUser">
                    </div>
                    <div class="form-group">

                        <label for="txtPass">Contraseña:</label>
                        <input placeholder="Ej: 1234" class="form-control" type="password"  id="txtPass" name="txtPass">    
                    </div>
                        
                        
                        
                    <a href="{% url 'login' %}" class="btn btn-info" style="background-color: blueviolet; border: none; " role="button">Enviar</a>
                    <a href="" class="btn btn-info" style="background-color: rgb(205, 92, 0); border: none; " role="button">Limpiar</a>
                    
                    
                  
                </form>
            </div>
      
            <div class="modal-footer">
                <a href="{% url 'index' %}" style="color: black; margin-right: 50%;">¿Aún no tiene cuenta?</a>
                <a href="{% url 'index' %}" class="btn btn-info" style="background-color: rgb(205, 92, 0); border: none; " role="button">Cerrar</a>
             
            </div>
      
          </div>
        </div>
    </div>






    <nav class="navbar navbar-expand-sm navbar-dark pnav">
        <div class="container-fluid">
            <a class="navbar-brand" href="#"><img src="{% static 'app/img/ceee.png' %}" alt="" style="border-radius: 50%; height: 100px;"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <ul class="nav mt-1">
                <li>
                    <h1>PetShop</h1>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#"><i class="fa-brands fa-instagram"></i></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#"><i class="fa-brands fa-facebook"></i></a>
                </li>
              </ul>

            
            <div class="collapse navbar-collapse justify-content-end" id="collapsibleNavbar">
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                    
                        
                    <li>Bienvenido: {{ user.username }}</li>
                        
                    
                    {% endif %}
                    <li class="nav-item">
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'suscripcion' %}" style="color: white;">Suscribete</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'ayuda' %}" style="color: white;">¿Necesitas ayuda?</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>







        
            {% block contenido %}

            {% endblock %}

        
        
        
        </div>






    </div>







    <div class="p-5 bg-dark text-white ">
        <div class="d-flex justify-content-between align-items-center">
            <img src="{% static 'app/img/Logo2.jpg'%}" alt="" height="150" width="400" >
            <img src="{% static 'app/img/mascprot.png'%}" alt="" height="100">
        </div>
    </div>

    <!-- Latest compiled JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>

app/templates/app/carrito.html
{% extends 'app/base_iniciado.html' %}
{% load static %}


{% block contenido %}




<div class="col-sm-10" >
    <div class="row">
        <div class="col-sm-1"></div>
        <div class="col-sm-10" style="margin-top: 30px;">
            
            <table class="table table-dark table-hover">
                <thead>
                    <tr class="text-primary">
                        <th scope="col">Productos</th>
                        <th scope="col">Precio</th>
                        <th scope="col">Cantidad</th>
                        <th scope="col">Eliminar</th>
                        <th scope="col">Comprar</th>
                    </tr>
                </thead>

                <tbody>
                    {% for aux in listaCarrito %} 
                    <tr>
                        <td class="Producto">
                            <img src="{{aux.imagen.url}}"  alt="" height="100px">
                            <h6>{{aux.nombre_producto}}</h6>
                        </td>
                        <td 
                            class="Precio"> <p>{{aux.precio_producto}}</p>
                        </td>
                        <td class="Cantidad">
                            
                            <input type="number" name="1" value="1">

                        </td>

                        <td class="Cantidad">
                            
                        {% if perms.app.delete_producto %} 
                            <a href="{% url 'eliminar_carrito' aux.id %}" class= "btn btn-danger">Eliminar</a>
                        {% endif %}

                        </td>
                        <td class="Cantidad">
                            
                            <form action="" method="POST"> 
                                {% csrf_token %}
                                <input type="hidden" name="nombre_producto" id="" value="{{aux.nombre_producto}}">
                                <input type="hidden" name="precio_producto" id="" value="{{aux.precio_producto}}">
                                <input type="hidden" name="imagen_producto" id="" value="{{aux.imagen.url}}">
                                
                                <input type="submit" style="cursor: pointer; " class="btn btn-success btn-sm ml-auto" href="{% url 'pago' %}">
                    
                        
                            </form>

                        </td>

                        {% endfor %}
                         
                    </tr>
            

                </tbody>
            </table>
            <br>
            <br>
            <div class="row mx-4">
                <div class="col">
                    
                
                    <h3 class="cartotal text-white">Sub-Total: {{ precio }}</h3> 
                    <h3 class="cartotal text-white">descuento: {{ descuento }}</h3> 
                    <h3 class="cartotal text-white">Total: {{ total }}</h3> 
                    
                    
                </div>
                <div class="col d-flex justify content-end">
 
                    <a href="{% url 'pago' %}"> <button class="btn btn-success">Comprar</button> </a>
                </div>

                
                
                
                <a href="{% url 'usu_ini' %}">
                    <button style="background-color: rgb(129, 16, 190); border: none;" class="btn btn-primary" activated>
                    <span  class="spinner-grow spinner-grow-sm"></span>
                    Volver al Inicio
                    </button>
                    </a>
                </div>

            </div>
              <div class="col-sm-1"></div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12"></div>
    </div>
</div>
</div>
</div>
   
</div>

{% endblock %}

app/templates/app/cuenta.html
{% extends 'app/base_iniciado.html' %}
{% load static %}


{% block contenido %}




  

<div class="col-sm-10" >
    <div class="row">
        <div class="container mt-3" style="color: white;">
            <h2>Perfil</h2>
            
            <div class="media border p-3">
              <img src="{% static 'app/img/ben-brereton-laroja-chile-venezuela-catar2022-c.jpg' %}" alt="John Doe" class="mr-3 mt-3 rounded-circle" style="width:400px;">
              <div class="media-body">
                  
                  
                  
                <h4 style="color: white;">Nombre:  <i>Benjamin Brereton Díaz</i></h4>
                <br>   
                <h4 style="color: white;">Rut: <i>20.666.123-K</i></h4>
                <br>
                <h4 style="color: white;">Direccion: <i>Stoke-on-Trent, Reino Unido</i></h4>
                 <br>    
                <h4 style="color: white;">Correo Electronico: <i>benjita_22@gmail.com</i></h4>
                     
                     
              </div>
            </div>
          </div>
                

          <a href="{% url 'usu_ini' %}">
            <br>
            <br>
            <button style="background-color: rgb(129, 16, 190); border: none; margin-left: 20px; color: white;" class="btn btn-primary;" activated>
            <span  class="spinner-grow spinner-grow-sm"></span>
            Volver al Inicio
            </button>
            </a>

                

            </div>
            <br>
                <br>
                <br>
                <br>
              <div class="col-sm-1"></div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12"></div>
    </div>
</div>
</div>
</div>

</div>

{% endblock %}

app/templates/app/historial.html
{% extends 'app/base_iniciado.html' %}
{% load static %}


{% block contenido %}




<div class="col-sm-10" >
    <div class="row">
        <div class="col-sm-1"></div>
        <div class="col-sm-10" style="margin-top: 30px;">
            
            <table class="table table-dark table-hover">
                <thead>
                    <tr class="text-primary">
                        <th scope="col">Productos</th>
                        <th scope="col">Precio</th>
                        <th scope="col">Cantidad</th>
                        <th scope="col">Comprar</th>
                    </tr>
                </thead>
                <tbody>
                    {% for aux in listahistorial %} 
                    <tr>
                        <td class="Producto">
                            <img src="{{aux.imagen.url}}"  alt="" height="100px">
                            <h6>{{aux.nombre_producto}}</h6>
                        </td>
                        <td 
                            class="Precio"> <p>{{aux.precio_producto}}</p>
                        </td>
                        <td class="Cantidad">
                            
                            <input type="number" name="1" value="1">

                        </td>

                        {% endfor %} 
                    </tr>
            

                </tbody>
            </table>
            <br>
            <br>
            <div class="row mx-4">
                <div class="col">
                    

                    <h3 class="cartotal text-white">Total:{{aux.precio_producto}}</h3>
                    
                </div>
                <div class="col d-flex justify content-end">
 
                    <a href="{% url 'pago' %}"> <button class="btn btn-success">Comprar</button> </a>
                </div>

                
                
                
                <a href="{% url 'usu_ini' %}">
                    <button style="background-color: rgb(129, 16, 190); border: none;" class="btn btn-primary" activated>
                    <span  class="spinner-grow spinner-grow-sm"></span>
                    Volver al Inicio
                    </button>
                    </a>
                </div>

            </div>
              <div class="col-sm-1"></div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12"></div>
    </div>
</div>
</div>
</div>
   
</div>

{% endblock %}

app/templates/app/index.html
{% extends 'app/base_iniciado.html' %}
{% load static %}


{% block contenido %}



<div class="col-sm-10">
    <div class="row">
        <div class="col-sm-1"></div>
        <div class="col-sm-10" style="margin-top: 30px;">
            
            <div id="demo" class="carousel slide" data-ride="carousel">

                <!-- Indicators -->
                <ul class="carousel-indicators">
                  <li data-target="#demo" data-slide-to="0" class="active"></li>
                  <li data-target="#demo" data-slide-to="1"></li>
                  <li data-target="#demo" data-slide-to="2"></li>
                </ul>
              
                <!-- The slideshow -->
                <div class="carousel-inner">
                  <div class="carousel-item active">
                    <img src="{% static 'app/img/msc1.jpg'%}" style="width: 800px;" height="200px" alt="im1">
                  </div>
                  <div class="carousel-item">
                    <img src="{% static 'app/img/mdsc2.jpg'%}" style="width: 800px;" height="200px"  alt="img2">
                  </div>
                  <div class="carousel-item">
                    <img src="{% static 'app/img/msc3.jpg'%}" style="width: 800px;" height="200px" alt="img3">
                  </div>
                </div>
              
                <!-- Left and right controls -->
                <a class="carousel-control-prev" href="#demo" data-slide="prev">
                    <span class="carousel-control-prev-icon"></span>
                  </a>
                  <a class="carousel-control-next" href="#demo" data-slide="next">
                    <span class="carousel-control-next-icon"></span>
                  </a>
                
                </div>
  
                <br> 
                <br>
  
                
  
  
  
                  
                  <div class="row row-cols-sm-1 row-cols-md-2 row-col-lg-3 row-cols-xl-4" > 
                      {% for aux in listaProductos %} 
                      
                              <div class="col d-flex justify-content-center   mb-4" >
                                  <div class="card sadow mb-1 bg-dark rounded" style="width: 20rem; ">
                                  
                                      <h5 class="card-titulo pt-2 text-center text-primary" style="margin-bottom: 54px">{{aux.nombre}}</h5>
                                      {% if aux.imagen %}
                                      <img src="{{ aux.imagen.url }}" class="card-img-top imgp" alt="">
                                      {% else %}
                                      <img src="{% static 'app/img/G1.avif' %}" class="card-img-top imgp" alt="">
                                      {% endif %}
                                      
                                      
                                      
                                      
                                      
                                      <div class="card-body text-white-50" >
                                          <p class="card-text description">{{aux.marca}}</p>
                                          <h5 class="precio" style="color: rgb(255, 255, 255);">Precio: $<span class="precio">{{aux.precio}}</span></h5>
                                          <p class="cantidad"> Stock: {{aux.stock}}</p>
  
                                          <form action="" method="POST"> 
                                            {% csrf_token %}
                                            <input type="hidden" name="nombre_producto" id="" value="{{aux.nombre}}">
                                            <input type="hidden" name="precio_producto" id="" value="{{aux.precio}}">
                                            <input type="hidden" name="imagen_producto" id="" value="{{aux.imagen}}">
        
        
        
                                            <h6 style="color: rgb(255, 255, 255); background-color: rgb(95, 0, 133); padding: 10%; border-radius: 20%;"> Nota: Inicie sesion para poder comprar</h6>
                                          
                                        </form>
                                          
                                      </div>
                                  </div>
                              </div> 
  
  
                      {% endfor %}
                  </div>
                  
  
  
  
  
          </div>
      </div>
      <div class="row">
          <div class="col-sm-12"></div>
      </div>
  </div>
  
  {% endblock %}
  
  

app/templates/app/listar_producto.html
{% extends 'app/base_iniciado.html' %}
{% load static %}


{% block contenido %}








<script>
    function confirmDelete(codigo){
  Swal.fire({
    title: 'Are you sure?',
    text: "You won't be able to revert this!",
    icon: 'warning',
    showCancelButton: true,
    confirmButtonColor: '#3085d6',
    cancelButtonColor: '#d33',
    confirmButtonText: 'Yes, delete it!'
  }).then((result) => {
    if (result.isConfirmed) {
      Swal.fire(
        'Deleted!',
        'Your file has been deleted.',
        'success'
      ).then(function (){
        window.location.href = "/eliminar_producto/"+ codigo + "/"
      })
    }
  })
}

</script>


<div class="col-sm-10" >
    <div class="row">
        <div class="col-sm-1"></div>
        <div class="col-sm-10" style="margin-top: 30px; ">
            
            <div class="container" style="color: white;">
                <h2>Listar producto</h2>
                {% if perms.app.add_producto %} 
                <a href="{% url 'agregar_p' %}" class="btn btn-bg-danger" style="color: white">agregar producto</a>
                {% endif %}
                <table class="table table-dark table-striped">

                    <thead>
                        <tr>
                            <th>CODIGO</th>
                            <th>NOMBRE</th>
                            <th>MARCA</th>
                            <th>PRECIO</th>
                            <th>STOCK</th>
                            <th>TIPO</th>
                            <th>IMAGEN</th>
                            <th>FECHA CREACION</th>
                            <th>FECHA MODIFICACION</th>
                            <th>OPCIONES</th>
                
                        </tr>
                    </thead>
                    <tbody>
                        {% for aux in listaProductos %}
                        <tr>
                            <td>{{aux.codigo}}</td>
                            <td>{{aux.nombre}}</td>
                            <td>{{aux.marca}}</td>
                            <td>{{aux.precio}}</td>
                            <td>{{aux.stock}}</td>
                            <td>{{aux.tipo}}</td>
                            <td>
                              {% if aux.imagen %}
                                <img src="{{ aux.imagen.url }}" class="card-img-top imgp" alt="" >
                              {% else %}
                                <img src="{% static 'app/img/G1.avif' %}" class="card-img-top imgp" alt="">
                              {% endif %}
                            </td>  
                            <td>{{aux.created_at}}</td>
                            <td>{{aux.updated_at}}</td>
                            <td>

                              {% if perms.app.change_producto %}     
                              <a href="{% url 'modificar_producto' aux.codigo %}" class="btn btn-info">Modificar</a>

                              {% endif %}
                           <br>
                           <br>
                              {% if perms.app.delete_producto %} 
                                <a onclick="confirmDelete({{aux.codigo}})" class= "btn btn-danger">Eliminar</a>
                              {% endif %}
                            </td>
                    
                    
                    
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

{% endblock %}

app/templates/app/listar_usuarios.html
{% extends 'app/base_iniciado.html' %}
{% load static %}


{% block contenido %}




<div class="col-sm-10" >
    <div class="row">
        <div class="col-sm-1"></div>
        <div class="col-sm-10" style="margin-top: 30px; ">
            
            <div class="container" style="color: white;">
                <h2>Lista de usuarios</h2>
                <table class="table table-dark table-striped">
                    <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Apellido</th>
                            <th>Rut</th>
                            <th>Direccion</th>
                            <th>correo</th>
                            <th>contrasenia</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for aux in listausuarios %}
                        <tr>
                            <td>{{aux.nombre}}</td>
                            <td>{{aux.apellido}}</td>
                            <td>{{aux.rut}}</td>
                            <td>{{aux.direccion}}</td>
                            <td>{{aux.correo}}</td>
                            <td>{{aux.contrasenia}}</td>

                            <td>
                                <a href="{% url 'modificar_usuarios' aux.rut %}" class="btn btn-info">Modificar</a>
                           <br>
                           <br>
                                <a onclick="confirmDelete({{aux.rut}})" class= "btn btn-danger">Eliminar</a>
                            </td>
                    
                    
                    
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

{% endblock %}

app/templates/app/modificar_usuarios.html
{% extends 'app/base_iniciado.html' %}
{% load static %}


{% block contenido %}


<div class="col-sm-10" >
    <div class="row">
        <div class="col-sm-1"></div>
        <div class="col-sm-10" style="margin-top: 30px;">
            
            <div class="container" style="color: white;">
                <h2>Registrate</h2>
                    
            
            
                    <!-- Modal body -->
                    <div class="modal-body">
                        <div style="text-align: center;">
                          
                          <form action="" method="POST" enctype="multipart/form-data">
                              {% csrf_token %}
                              <table>
                                {{ forms }}
                              </table>
                              <input type="submit" class="btn btn-primary" style="background-color: rgb(117, 30, 167);border: none;" value="Guardar">
                          </form>  
                          {{ mensajito }}     
                          
                              
                            
                        </div>
                    </div>
            
                </div>
                </div>
            </div>
            
                <a href="Usuario_Iniciado.html">
                <button class="btn btn-primary" style="background-color: rgb(117, 30, 167); border: none; margin-bottom: 20px;"> 
                <span class="spinner-grow spinner-grow-sm"></span>
                Volver al Inicio
                </button>
                </a>

                
            </div>
              <div class="col-sm-1"></div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12"></div>
    </div>
</div>

{% endblock %}